apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  annotations:
    container.apparmor.security.beta.kubernetes.io/hello: localhost/k8s-apparmor-example-deny-write
spec:
  containers:
    - name: hello
      image: busybox:1.28
      command: ["sh", "-c", "sleep 1h"]
